### ISSUE TITLE
No module named 'utils.compute_overlap'

### ISSUE THREAD

**Issue by nicholasguimaraes** [xuannianz/EfficientDet#11]
Hello, firstly thank you for the great work. 

I am having trouble starting training. I get this error:

-- No module named 'utils.compute_overlap' --

I have the keras-retinanet running perfectly on my machine. 

What could be done?

Regards!

**Comment by xuannianz** [comment]
Hi @nicholasguimaraes , could you replace the compute_overlap.so of this repo with the one from keras-retinanet?
If it still does not work, try to rebuild it by running the `setup.py` script from keras-retinanet.
Wait for your feedback.

**Comment by nicholasguimaraes** [comment]
Thank you for your reply.

In fact I don't have a compute_overlap.so file under keras-retinanet/utils.

I do have a compute_overlap.c ,  .pyd  and   .pyx. 

I tried replacing the compute_overlap.pyx  from  EfficientDet/utils with the .pyx from RetinaNet/utils and I was able to start training but, I got an AssertionError after the first step.

**Comment by HaiLongEmb** [comment]
How to solve the same problem on Windows  @xuannianz ，
![222](https://user-images.githubusercontent.com/32731062/70111138-537aa300-168c-11ea-96de-b74854460049.jpg)

**Comment by nikola-j** [comment]
I've fixed it by renaming the "compute_overlap.cython-36m-x86_64-linux-gnu.so" to "compute_overlap.so"

**Comment by xuannianz** [comment]
@nikola-j Do it really work on Windows?
@HaiLongEmb How about running `python setup.py build_ext --inplace` to rebuild the module?

**Comment by nikola-j** [comment]
@xuannianz I'm on ubuntu 18.04

**Comment by nicholasguimaraes** [comment]
Hello @xuannianz , I am also on Windows. 

After running "python setup.py build_ext --inplace"  I got the file "compute_overlap.cp36-win_amd64.pyd" which I renamed to "compute_overlap.pyd". I added the .pyd from retinanet/utils to efficientdet/utils and I was able to start training but soon I get another Error. 

"""

Traceback (most recent call last):
  File "train.py", line 352, in <module>
    main()
  File "train.py", line 347, in main
    validation_data=validation_generator
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 293, in model_iteration
    callbacks._call_batch_hook(mode, 'end', step, batch_logs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\callbacks.py", line 248, in _call_batch_hook
    batch_hook(batch, logs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\callbacks.py", line 531, in on_train_batch_end
    self.on_batch_end(batch, logs=logs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\callbacks_v1.py", line 362, in on_batch_end
    profiler.save(self.log_dir, profiler.stop())
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\eager\profiler.py", line 144, in save
    gfile.MakeDirs(plugin_dir)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 438, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 453, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: logs/2019-12-05\plugins\profile\2019-12-05_14-18-11; No such file or directory

"""

Has anyone gotten the same error?

**Comment by nicholasguimaraes** [comment]
> random_misc_group_entry
> assert annotations['bboxes'].shape[0] != 0
> AssertionError

Regarding the AssertionError I got a few days ago, it happened because I tried using background images with no x1,y1,x2,y2

**Comment by xuannianz** [comment]
@nicholasguimaraes You can pull the latest code in which I removed that assertion.

**Comment by nicholasguimaraes** [comment]
> 
> 
> @nicholasguimaraes You can pull the latest code in which I removed that assertion.

I just pulled the latest code. 

It seems that I cannot train without validation data. 

"""
Traceback (most recent call last):
  File "train.py", line 355, in <module>
    main()
  File "train.py", line 350, in main
    validation_data=validation_generator
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 220, in model_iteration
    batch_data = _get_next_batch(generator, mode)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 362, in _get_next_batch
    generator_output = next(generator)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\utils\data_utils.py", line 785, in get
    six.reraise(*sys.exc_info())
  File "C:\Users\Windows\AppData\Roaming\Python\Python36\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\utils\data_utils.py", line 779, in get
    inputs = self.queue.get(block=True).get()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\utils\data_utils.py", line 571, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "C:\Users\Windows\Documents\EfficientDet\generators\common.py", line 392, in __getitem__
    inputs, targets = self.compute_inputs_targets(group)
  File "C:\Users\Windows\Documents\EfficientDet\generators\common.py", line 348, in compute_inputs_targets
    image_group = self.load_image_group(group)
  File "C:\Users\Windows\Documents\EfficientDet\generators\common.py", line 219, in load_image_group
    return [self.load_image(image_index) for image_index in group]
  File "C:\Users\Windows\Documents\EfficientDet\generators\common.py", line 219, in <listcomp>
    return [self.load_image(image_index) for image_index in group]
  File "C:\Users\Windows\Documents\EfficientDet\generators\csv_.py", line 225, in load_image
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

"""

I'm not passing compute_val_loss as an argument.

This is my line to start training:

python train.py --phi 0 --freeze-backbone csv bin/csv_label/annotations.csv bin/csv_label/classes.csv

**Comment by xuannianz** [comment]
Check the image paths in your csv file.

**Comment by nicholasguimaraes** [comment]
> 
> 
> Check the image paths in your csv file.

The image path is correct. I wonder if using .gif images could be the problem.

I use the same dataset to train retinanet and we works fine.

**Comment by nicholasguimaraes** [comment]
I fixed it!

On generators/csv_.py   I updated the function load_image to load images with PIL instead of cv2, but that was not the solution. 

I had to go to
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Lib\site-packages\tensorflow\python\lib\io

and update file_io.py , more specifically the function recursive_create_dir_v2.

that's what it looks now:

def recursive_create_dir_v2(path):
  #print(path)
  dest_log = "C:\\Users\\Windows\\Documents\\EfficientDet\\logs\\"
  path_new = path.replace("logs/","")
  path_new =  path_new.replace(chr(92), "\\")
  path = dest_log+path_new

Turns out it was simply a path error. I hope this can help all windows users.

**Comment by gabriel-zly** [comment]
> Hello @xuannianz , I am also on Windows.
> 
> After running "python setup.py build_ext --inplace" I got the file "compute_overlap.cp36-win_amd64.pyd" which I renamed to "compute_overlap.pyd". I added the .pyd from retinanet/utils to efficientdet/utils and I was able to start training but soon I get another Error.
> 
> """
> 
> Traceback (most recent call last):
> File "train.py", line 352, in 
> main()
> File "train.py", line 347, in main
> validation_data=validation_generator
> File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1433, in fit_generator
> steps_name='steps_per_epoch')
> File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 293, in model_iteration
> callbacks._call_batch_hook(mode, 'end', step, batch_logs)
> File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\callbacks.py", line 248, in _call_batch_hook
> batch_hook(batch, logs)
> File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\callbacks.py", line 531, in on_train_batch_end
> self.on_batch_end(batch, logs=logs)
> File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\keras\callbacks_v1.py", line 362, in on_batch_end
> profiler.save(self.log_dir, profiler.stop())
> File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\eager\profiler.py", line 144, in save
> gfile.MakeDirs(plugin_dir)
> File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 438, in recursive_create_dir
> recursive_create_dir_v2(dirname)
> File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 453, in recursive_create_dir_v2
> pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path))
> tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: logs/2019-12-05\plugins\profile\2019-12-05_14-18-11; No such file or directory
> 
> """
> 
> Has anyone gotten the same error?
Sorry, I didn’t see the file set.py in the code. Could you send me this? Thank you!

**Comment by kumbarisagar** [comment]
when i run a inference.py i am getting a error as no module named compute_overlap 
what to do? when we encounter this in inference.py

**Comment by kumbarisagar** [comment]
please reply back i need urgent reply
