### ISSUE TITLE
What is the cause of this mistake？

### ISSUE THREAD

**Issue by kongxm889** [xuannianz/EfficientDet#115]
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Traceback (most recent call last):
  File "train.py", line 377, in <module>
    main()
  File "train.py", line 314, in main
    detect_quadrangle=args.detect_quadrangle
  File "/home/kxm/EfficientDet-master/model.py", line 241, in efficientdet
    class_head = build_class_head(w_head, d_head, num_classes=num_classes, num_anchors=num_anchors)
  File "/home/kxm/EfficientDet-master/model.py", line 211, in build_class_head
    )(outputs)
  File "/home/kxm/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "/home/kxm/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1603, in _maybe_build
    self.build(input_shapes)
  File "/home/kxm/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py", line 174, in build
    dtype=self.dtype)
  File "/home/kxm/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 349, in add_weight
    aggregation=aggregation)
  File "/home/kxm/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 607, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/kxm/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 145, in make_variable
    aggregation=aggregation)
  File "/home/kxm/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 213, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/kxm/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 176, in _variable_v1_call
    aggregation=aggregation)
  File "/home/kxm/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 155, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/kxm/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2488, in default_variable_creator
    import_scope=import_scope)
  File "/home/kxm/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 217, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/kxm/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 294, in __init__
    constraint=constraint)
  File "/home/kxm/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 406, in _init_from_args
    initial_value() if init_from_fn else initial_value,
  File "/home/kxm/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 127, in <lambda>
    shape, dtype=dtype, partition_info=partition_info)
TypeError: __call__() got an unexpected keyword argument 'partition_info'

**Comment by xuannianz** [comment]
Hi @kongxm889 , which tf version are you using? You can try under tf 1.15 and tf 2.x.

**Comment by kongxm889** [comment]
但是又出现啦以下提示：python: symbol lookup error: /home/kxm/anaconda3/lib/python3.6/site-packages/numpy/core/../../../../libmkl_intel_thread.so: undefined symbol: omp_get_num_procs

**Comment by kongxm889** [comment]
However, the following prompt appears:python: symbol lookup error: /home/kxm/anaconda3/lib/python3.6/site-packages/numpy/core/../../../../libmkl_intel_thread.so: undefined symbol: omp_get_num_procs

**Comment by xuannianz** [comment]
I have no idea. But you can try this https://github.com/ContinuumIO/anaconda-issues/issues/10195#issuecomment-429544158

**Comment by kongxm889** [comment]
i,don't know,this is my mistakes
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node stem_conv/Conv2D}}]]
	 [[filtered_detections/map/while/Identity/_2790]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node stem_conv/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

**Comment by kongxm889** [comment]
ValueError: Layer #337 (named "box_head"), weight <tf.Variable 'conv2d_3/kernel:0' shape=(3, 3, 64, 108) dtype=float32> has shape (3, 3, 64, 108), but the saved weight has shape (36, 64, 3, 3).

What's the problem

**Comment by SiBensberg** [comment]
@kongxm889 I had the same problem some time ago. For me it was a problem with cuda and anaconda. The post from Bahramudin solved it: https://github.com/tensorflow/tensorflow/issues/24828
