### ISSUE TITLE
Error in loading pre-trained model

### ISSUE THREAD

**Issue by zgzxy001** [xuannianz/EfficientDet#116]
Thanks for your amazing work! I met the following error when I load the coco pre-trained weights "efficientdet-d2.h5".

Loading model, this may take a second...
Traceback (most recent call last):
  File "train.py", line 381, in <module>
    main()
  File "train.py", line 333, in main
    model.load_weights(args.snapshot, by_name=True)
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/keras/engine/training.py", line 182, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/keras/engine/network.py", line 1371, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, self.layers)
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/keras/saving/hdf5_format.py", line 745, in load_weights_from_hdf5_group_by_name
    str(len(weight_values)) + ' element(s).')
ValueError: Layer #334 (named "fpn_cells/cell_0/fnode0/add") expects 0 weight(s), but the saved weights have 1 element(s).

Here is the cmd to reproduce the error:
!python train.py --snapshot "./weights/efficientdet-d2.h5" --phi 2 --gpu 0 --epochs 3 --random-transform --compute-val-loss --freeze-backbone --batch-size 4 --steps 300 --snapshot-path "./logs/" --tensorboard-dir  "./tensorboard/" coco "./data/" 

And the same error happens for phi=4. I have not tested other pre-trained models. But it does not show any error when I use "--snapshot imagenet". 

Thank you very much!

**Comment by xuannianz** [comment]
Hi, @zgzxy001 . You need to specify `--weighted-bifpn` when use pretrained coco.
