### ISSUE TITLE
How to avoid CUDA_ERROR_OUT_OF_MEMORY: out of memory, when --phi = 1?

### ISSUE THREAD

**Issue by sliawatimena** [xuannianz/EfficientDet#150]
Dear all,

My environment: Windows 10, RAM 32, Python 3.7.4, CUDA 11.0, nvcc (Cuda compilation tools, release 10.0, V10.0.130), RTX2060, Driver Version: 445.75, tensorflow-gpu==1.15.0
I got CUDA_ERROR_OUT_OF_MEMORY: out of memory when using --phi = 1

How to solve this problem?
Thank you very much in advance.

Warmest regards,
Suryadi

`
python train.py --epochs 2 --snapshot imagenet --phi 1 --gpu 0 --random-transform --compute-val-loss --freeze-backbone --batch-size 8 --steps 2 pascal D:\learn\pascal\VOCtrainval_11-May-2012\VOCdevkit\VOC2012\
(many lines are deleted here)
Total params: 7,225,352
Trainable params: 1,057,976
Non-trainable params: 6,167,376
__________________________________________________________________________________________________
None
Ada tensorboard_callback =  <tensorflow.python.keras.callbacks_v1.TensorBoard object at 0x000001FC8C43A308>
Epoch 1/2
2020-04-16 00:59:01.269505: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-04-16 00:59:02.332008: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: Invoking ptxas not supported on Windows
Relying on driver to perform ptx compilation. This message will be only logged once.
2020-04-16 00:59:02.431162: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-04-16 00:59:03.204061: W tensorflow/core/common_runtime/bfc_allocator.cc:305] Garbage collection: deallocate free memory regions (i.e., allocations) so that we can re-allocate a larger region to avoid OOM due to memory fragmentation. If you see this message frequently, you are running near the threshold of the available device memory and re-allocation may incur great performance overhead. You may try smaller batch sizes to observe the performance impact. Set TF_ENABLE_GPU_GARBAGE_COLLECTION=false if you'd like to disable this feature.
2020-04-16 00:59:03.263676: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 3.50G (3757506560 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-16 00:59:06.194695: I tensorflow/core/profiler/lib/profiler_session.cc:205] Profiler session started.
2020-04-16 00:59:06.198217: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cupti64_100.dll
1/2 [==============>...............] - ETA: 11s - loss: 4.2019 - regression_loss: 2.8140 - classification_loss: 1.38802020-04-16 00:59:06.774271: I tensorflow/core/platform/default/device_tracer.cc:588] Collecting 2822 kernel records, 11 memcpy records.
Traceback (most recent call last):
  File "train.py", line 388, in <module>
    main()
  File "train.py", line 383, in main
    validation_data=validation_generator
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\engine\training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\engine\training_generator.py", line 294, in model_iteration
    callbacks._call_batch_hook(mode, 'end', step, batch_logs)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\callbacks.py", line 236, in _call_batch_hook
    batch_hook(batch, logs)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\callbacks.py", line 519, in on_train_batch_end
    self.on_batch_end(batch, logs=logs)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\callbacks_v1.py", line 362, in on_batch_end
    profiler.save(self.log_dir, profiler.stop())
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\eager\profiler.py", line 140, in save
    gfile.MakeDirs(plugin_dir)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\lib\io\file_io.py", line 438, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\lib\io\file_io.py", line 453, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: logs/2020-04-16\plugins\profile\2020-04-16_00-59-06; No such file or directory
`

**Comment by AutumnZ-94** [comment]
The validation dataset is usually fed in GPU in 1 batch, try to train without `compute_val_loss`,   if you have a large validation data. So that GPU would load traning data only. Then you can manually calculate the mAP when you need.

**Comment by SiBensberg** [comment]
Try smaller batch size. But then you should probably add the -freeze-bn option. Because batch normalization does not work good with small batches. What puzzles me the RTX2060 should have enough RAM for batchsize=8 are other programs running on the GPU?
