### ISSUE TITLE
OOM issue

### ISSUE THREAD

**Issue by neuhzhj2012** [xuannianz/EfficientDet#17]
Hi. I try to train pascal model using phi=6, but OOM happens.
First, for step 1, there is always OOM when batch_size is bigger than 1. Try to let batch_size equals  {16, 8, 4, 2}, they all face the same issue. At last，when I set batch_size = 1, the training process goes well.
Second, for step 2, It is always OOM even when I set batch_size = 1. Following the Readme ,I chose model at epoch 20 as the value of snapshot. This time the OOM issue appears again.
ps: I use Tesla V100 to train the model.
Any advices?

```
2019-12-06 03:05:27.140466: I tensorflow/core/common_runtime/bfc_allocator.cc:818] total_region_allocated_bytes_: 15651091200 memory_limit_: 15651091252 available bytes: 52 curr_region_allocation_bytes_: 17179869184
2019-12-06 03:05:27.140496: I tensorflow/core/common_runtime/bfc_allocator.cc:824] Stats: 
Limit:                 15651091252
InUse:                 15641373952
MaxInUse:              15646383616
NumAllocs:                    6516
MaxAllocSize:            380633088

2019-12-06 03:05:27.141000: W tensorflow/core/common_runtime/bfc_allocator.cc:319] ****************************************************************************************************
2019-12-06 03:05:27.141056: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at transpose_op.cc:199 : Resource exhausted: OOM when allocating tensor with shape[1,88,88,864] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "train.py", line 355, in <module>
    main()
  File "train.py", line 350, in main
    validation_data=validation_generator
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_generator.py", line 264, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 1175, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[1,864,88,88] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node block5a_expand_bn/FusedBatchNorm}}]]
```

**Comment by xuannianz** [comment]
There are more trainable params in step 2 so you need more gpu memory.

**Comment by 2696120622** [comment]
I encounter a similar issue, have you solved it?
Limit:                 11330115994
InUse:                 10303743232
MaxInUse:              10303743232
NumAllocs:                    1580
MaxAllocSize:           1275068416

2019-12-06 14:47:07.208318: W tensorflow/core/common_runtime/bfc_allocator.cc:424] **********************************************************************_____************************_
2019-12-06 14:47:07.208619: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at cwise_ops_common.cc:82 : Resource exhausted: OOM when allocating tensor with shape[32,96,320,320] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

**Comment by 2696120622** [comment]
> There are more trainable params in step 2 so you need more gpu memory.

Why retinanet or maskrcnn can be trained well with more trainable parameters than EfficientDet-D5 or D6?

**Comment by neuhzhj2012** [comment]
@xuannianz thank you reply. 
Another question is that if there is a map showing the relation between efficientdet-d{1-6} and  its required gpu memory for batch_size=1.
For gpu Tesla V100,  is there a efficientdet model can be trained?
