### ISSUE TITLE
Wrong layer shape when loading checkpoint for inference

### ISSUE THREAD

**Issue by satulovsky** [xuannianz/EfficientDet#171]
Hi,

Thank you so much for the repo! 
I used it to train a single class model without problems, however, when I load a checkpoint for inference (after configuring the checkpoint model path and classes in 'inference_quad.py') I get this error:

Traceback (most recent call last):
  File "inference_quad.py", line 32, in <module>
    prediction_model.load_weights(model_path, by_name=True)
  File "/home/javier/.virtualenvs/efficientdet2/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 182, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/home/javier/.virtualenvs/efficientdet2/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1371, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, self.layers)
  File "/home/javier/.virtualenvs/efficientdet2/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 754, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #399 (named "class_net/class-predict"), weight <tf.Variable 'class_net/class_net/class-predict/pointwise_kernel:0' shape=(1, 1, 64, 12) dtype=float32> has shape (1, 1, 64, 12), but the saved weight has shape (1, 1, 64, 9).

Except for making the anchors explicit, all other arguments of 'efficientdet()' are the same as for training. Any idea why the architecture of the saved weights would be different from the one efficientdet() creates?

What puzzles me is that I can load the same checkpoint for continuing to train (in train.py)...

Thank you!

**Comment by satulovsky** [comment]
My bad!  found that out the issue was me not configuring the anchors the same way during training and inference. Sorry.

**Comment by cyrilzakka** [comment]
How did you fix it? I'm having the same error
