### ISSUE TITLE
about something wrong when run the function of "preprocess_image" 

### ISSUE THREAD

**Issue by huizhang2017** [xuannianz/EfficientDet#182]
When run this code:
image, scale, offset_h, offset_w = preprocess_image(image, image_size=image_size)
Error happens as follows:

Traceback (most recent call last):

  File "<ipython-input-1-d2e43604cd84>", line 1, in <module>
    runfile('/home/hzhang/anaconda3/envs/EfficientDet/EfficientDet-master/inference_quad.py', wdir='/home/hzhang/anaconda3/envs/EfficientDet/EfficientDet-master')

  File "/home/hzhang/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/hzhang/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/hzhang/anaconda3/envs/EfficientDet/EfficientDet-master/inference_quad.py", line 52, in <module>
    image, scale, offset_h, offset_w = preprocess_image(image, image_size=image_size)

**ValueError: not enough values to unpack (expected 4, got 2)

How to fix this problem?

**Comment by KamalChhirang** [comment]
This function was recently updated. It only returns image and scale now. 

Try: 

`image, scale = preprocess_image(image, image_size=image_size)`

**Comment by huizhang2017** [comment]
> This function was recently updated. It only returns image and scale now.
> Try:
> image, scale = preprocess_image(image, image_size=image_size)

Thanks, Now it works.

**Comment by vaibhavmehrotraml** [comment]
In `inference_frozen_graph.py`, the `offset_h` and `offset_w` variables are required for the `post_process_boxes` function, which also seems like a typo because utils has only `postprocess_boxes`
