### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'partition_info'

### ISSUE THREAD

**Issue by tianfengyijiu** [xuannianz/EfficientDet#20]
Start to train pascal VOC,and the error :
Traceback (most recent call last):
  File "train.py", line 355, in <module>
    main()
  File "train.py", line 297, in main
    freeze_bn=args.freeze_bn)
  File "E:\EfficientDet\model.py", line 232, in efficientdet
    class_head = build_class_head(w_head, d_head, num_classes=num_classes)
  File "E:\EfficientDet\model.py", line 204, in build_class_head
    )(outputs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\keras\engi
ne\base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\keras\engi
ne\base_layer.py", line 1603, in _maybe_build
    self.build(input_shapes)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\keras\laye
rs\convolutional.py", line 174, in build
    dtype=self.dtype)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\keras\engi
ne\base_layer.py", line 349, in add_weight
    aggregation=aggregation)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\training\c
heckpointable\base.py", line 607, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\keras\engi
ne\base_layer_utils.py", line 145, in make_variable
    aggregation=aggregation)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\variab
les.py", line 213, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\variab
les.py", line 176, in _variable_v1_call
    aggregation=aggregation)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\variab
les.py", line 155, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\variab
le_scope.py", line 2488, in default_variable_creator
    import_scope=import_scope)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\variab
les.py", line 217, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\resour
ce_variable_ops.py", line 294, in __init__
    constraint=constraint)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\resour
ce_variable_ops.py", line 406, in _init_from_args
    initial_value() if init_from_fn else initial_value,
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\keras\engi
ne\base_layer_utils.py", line 127, in <lambda>
    shape, dtype=dtype, partition_info=partition_info)
TypeError: __call__() got an unexpected keyword argument 'partition_info'

**Comment by xuannianz** [comment]
Check versions of your tf and keras. You can take a look at the `requirements.txt` file.

**Comment by balag59** [comment]
As @xuannianz mentioned, this does have something to do with tf versions and the way parameters are handled in the initializer used in 'model.py'. Specifically, in the "build_class_head" function inside of 'model.py', the 'bias_initializer' is the one that causes this issue. I was able to get around this by commenting this line out. You could try a different initializer like just 'zeros' instead of 'PriorProbability' and see if that works. However, I'm not sure how much of an impact this particular bias initializer has on this model so please check that with the authors and please double check everything I just said.

**Comment by tianfengyijiu** [comment]
Great! I use TensorFlow 1.14 and it works! But the other error occurs:
2019-12-09 16:45:00.705957: E tensorflow/core/platform/default/device_tracer.cc:
68] CUPTI error: CUPTI could not be loaded or symbol could not be found.
Traceback (most recent call last):
  File "train.py", line 355, in <module>
    main()
  File "train.py", line 350, in main
    validation_data=validation_generator
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\keras\engi
ne\training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\keras\engi
ne\training_generator.py", line 293, in model_iteration
    callbacks._call_batch_hook(mode, 'end', step, batch_logs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\keras\call
backs.py", line 248, in _call_batch_hook
    batch_hook(batch, logs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\keras\call
backs.py", line 531, in on_train_batch_end
    self.on_batch_end(batch, logs=logs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\keras\call
backs_v1.py", line 362, in on_batch_end
    profiler.save(self.log_dir, profiler.stop())
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\eager\prof
iler.py", line 144, in save
    gfile.MakeDirs(plugin_dir)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\lib\io\fil
e_io.py", line 438, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\lib\io\fil
e_io.py", line 453, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a direct
ory: logs/2019-12-09\plugins\profile\2019-12-09_16-45-00; No such file or direct
ory

**Comment by xbcReal** [comment]
add a parameter partition_info=None in the __call__ function of PriorProbability which is in the initializers.py can solve the problem.
