### ISSUE TITLE
Out Of Memory(OOM) issue

### ISSUE THREAD

**Issue by juppiiiii** [xuannianz/EfficientDet#204]
Dear everyone,

When I run step2 to batch 2 using 2 GPUs, I get an OOM error. What could be the reason?

GPU is Tesla V100-DGXS that has 32478MiB memory.
The backbone was not frozen.

~~~python3 
python3 train.py --snapshot check_backup/2020-07-21/coco_50_0.2864_0.2770.h5 --phi 6 \
                --random-transform --freeze-bn --gpu 0,1\
                --batch-size 2 --epochs 50 --steps 10000 \
                coco /workspace/daehee/a_object_detection/EfficientDet/datasets/coco
~~~

Below is the error message displayed on the terminal.

~~~
2020-08-17 05:45:10.447654: W tensorflow/core/common_runtime/bfc_allocator.cc:424] ****************************************************************************************************
2020-08-17 05:45:10.447693: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at constant_op.cc:172 : Resource exhausted: OOM when allocating tensor with shape[1,176,176,384] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "train.py", line 381, in <module>
    main()
  File "train.py", line 376, in main
    validation_data=validation_generator
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 265, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 1017, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[1,176,176,384] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node replica_0/efficientdet/class_net/class-3-bn-3/cond/FusedBatchNormV3}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions forcurrent allocation info.

         [[replica_0/efficientdet/classification/concat/_24955]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions forcurrent allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[1,176,176,384] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node replica_0/efficientdet/class_net/class-3-bn-3/cond/FusedBatchNormV3}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions forcurrent allocation info.

0 successful operations.
1 derived errors ignored.
~~~

thank you.

**Comment by YuraLi88** [comment]
I successfully perform finetuning phi=4 using frozen backbone and batch = 4 (Tesla T4 16 GB VRAM). 
Probably, mixed precision training will help you.
