### ISSUE TITLE
Unable to Train on Custom Dataset in Colab

### ISSUE THREAD

**Issue by cyrilzakka** [xuannianz/EfficientDet#219]
Hello,

Hope you're doing well. I tried cloning this repository on Github to try the model on a custom dataset, but I got the following error:
```
Traceback (most recent call last):
  File "train.py", line 381, in <module>
    main()
  File "train.py", line 376, in main
    validation_data=validation_generator
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_generator.py", line 221, in model_iteration
    batch_data = _get_next_batch(generator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_generator.py", line 363, in _get_next_batch
    generator_output = next(generator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/data_utils.py", line 789, in get
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/data_utils.py", line 783, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/data_utils.py", line 571, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/content/EfficientDet/generators/common.py", line 424, in __getitem__
    inputs, targets = self.compute_inputs_targets(group)
  File "/content/EfficientDet/generators/common.py", line 373, in compute_inputs_targets
    image_group = self.load_image_group(group)
  File "/content/EfficientDet/generators/common.py", line 225, in load_image_group
    return [self.load_image(image_index) for image_index in group]
  File "/content/EfficientDet/generators/common.py", line 225, in <listcomp>
    return [self.load_image(image_index) for image_index in group]
  File "/content/EfficientDet/generators/coco.py", line 131, in load_image
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.2) /io/opencv/modules/imgproc/src/color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'CvtHelper'
```

**Dataset:** My dataset is formatted in the exact same way as COCO but with different classes, as such under the annotations folder, I have a file named `instances_train2017.json` and under the images folder, I have my list of images. Temporarily, I cloned `instances_train2017.json` and renamed it to `instances_val2017.json` as a placeholder for the validation set. 

After running `pip install -r requirements.txt`, I tried running the following command: `!python3 train.py --snapshot imagenet --phi 0 --gpu 0 --random-transform --compute-val-loss --freeze-backbone --batch-size 16 --steps 100 coco datasets/coco` but I got the error mentioned above. I saw that #153 also had the same issue, but his solution is unclear.

**Comment by cyrilzakka** [comment]
**Update:** I was able to get it training for 1 epoch by rearranging the directory from '/content/EfficientDet/datasets/coco/images/frame_####' to 'datasets/coco/images/train2017/frame_####' but this fails after epoch 1 with the same error as above
