### ISSUE TITLE
AttributeError: module 'tensorflow.keras.layers' has no attribute 'ReLU'

### ISSUE THREAD

**Issue by chenxiao521** [xuannianz/EfficientDet#4]
Thanks for your code,I try to train the VOC data, and get this error.
Traceback (most recent call last):
  File "/home/bigdata/chenfangxiong/EfficientDet/model.py", line 189, in <module>
    model, prediction_model = efficientdet(phi=6, num_classes=20)
  File "/home/bigdata/chenfangxiong/EfficientDet/model.py", line 160, in efficientdet
    features = build_BiFPN(features, w_bifpn, i)
  File "/home/bigdata/chenfangxiong/EfficientDet/model.py", line 43, in build_BiFPN
    P3_in = ConvBlock(num_channels, kernel_size=1, strides=1, name='BiFPN_{}_P3'.format(id))(C3)
  File "/home/bigdata/chenfangxiong/EfficientDet/model.py", line 36, in ConvBlock
    f3 = layers.ReLU(name='{}_relu'.format(name))
AttributeError: module 'tensorflow.keras.layers' has no attribute 'ReLU'
can you tell your keras =?,tensorflow=?

**Comment by xuannianz** [comment]
Take a look at *requirements.txt*.
