### ISSUE TITLE
What is the environment of the code

### ISSUE THREAD

**Issue by wzs9717** [xuannianz/EfficientDet#48]
I meet an issue 
TypeError: __call__() got an unexpected keyword argument 'partition_info'

and I think it is caused by the different environments. I am using TF-gpu 1.13.1, Keras 1.0.7

**Comment by wzs9717** [comment]
full issue is as follow:
Traceback (most recent call last):
  File "train.py", line 373, in <module>
    main()
  File "train.py", line 315, in main
    freeze_bn=args.freeze_bn)
  File "/home/zhishneg/EfficientDet-master/model.py", line 232, in efficientdet
    class_head = build_class_head(w_head, d_head, num_classes=num_classes)
  File "/home/zhishneg/EfficientDet-master/model.py", line 204, in build_class_head
    )(outputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1603, in _maybe_build
    self.build(input_shapes)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 174, in build
    dtype=self.dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 349, in add_weight
    aggregation=aggregation)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpointable/base.py", line 607, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 145, in make_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 213, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 176, in _variable_v1_call
    aggregation=aggregation)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 155, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 2488, in default_variable_creator
    import_scope=import_scope)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 217, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 294, in __init__
    constraint=constraint)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 406, in _init_from_args
    initial_value() if init_from_fn else initial_value,
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 127, in <lambda>
    shape, dtype=dtype, partition_info=partition_info)
TypeError: __call__() got an unexpected keyword argument 'partition_info'

**Comment by JooHyungSon** [comment]
Keras==2.2.5
opencv-contrib-python==3.4.2.17
opencv-python==3.4.2.17
Pillow==6.2.0
tensorflow-gpu==1.15.0

**Comment by wzs9717** [comment]
> Keras==2.2.5
> opencv-contrib-python==3.4.2.17
> opencv-python==3.4.2.17
> Pillow==6.2.0
> tensorflow-gpu==1.15.0
> CUDA 10.0

great, problem solved!
