### ISSUE TITLE
inference.py error during load_weights

### ISSUE THREAD

**Issue by tripzero** [xuannianz/EfficientDet#54]
I get the following error when running inference.py.  I trained as per the instructions (only step on I was only able to get batch_size of 4 due to memory constraints):

`Traceback (most recent call last):
  File "inference.py", line 26, in <module>
    prediction_model.load_weights(model_path, by_name=True)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/engine/training.py", line 182, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/engine/network.py", line 1371, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, self.layers)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 754, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #1097 (named "class_head"), weight <tf.Variable 'pyramid_classification/kernel:0' shape=(3, 3, 384, 180) dtype=float32> has shape (3, 3, 384, 180), but the saved weight has shape (720, 384, 3, 3).
`
first train command:
`python3 train.py --snapshot imagenet --phi 6 --gpu 0 --random-transform --compute-val-loss --freeze-backbone --batch-size 4 --steps 999 coco datasets/coco/`

second train command:
`python3 train.py --snapshot snapshot.h5 --phi 6 --gpu 0 --random-transform --compute-val-loss --freeze-bn --batch-size 4 --steps 10000 coco datasets/coco/`

"snapshot.h5" is me adding a "save_weights" at the end of train.py as for some reason ModelCheckpoint callback never got called or failed to create any models :/

**Comment by ammaradel** [comment]
I got a similar error after running only step 1 of D5 (not enough memory to run step 2, even with batch size 1):

`Traceback (most recent call last):
  File "inference_hajj.py", line 26, in <module>
    prediction_model.load_weights(model_path, by_name=True)
  File "/home/riotu/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/home/riotu/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1422, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, self.layers)
  File "/home/riotu/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 820, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #1 (named "stem_conv"), weight <tf.Variable 'stem_conv/kernel:0' shape=(3, 3, 3, 32) dtype=float32> has shape (3, 3, 3, 32), but the saved weight has shape (48, 3, 3, 3).`

**Comment by ammaradel** [comment]
Resolved. I didn't modify line 11: `phi = 1`. When I put the correct value of phi, it worked.

**Comment by tripzero** [comment]
I used phi 6 for training and modified line 6 to get this error. Tried 5 in inference just for kicks and got a much different error

**Comment by xuannianz** [comment]
Hi @tripzero, you should set `num_classes=80` when you save weights for coco, the default value is 20. 
20 * 9 = 180, 80 * 9 = 720, so they do not match.

**Comment by sinclairnick** [comment]
Hey @xuannianz, do you mean `num_classes=90` since coco has 90 classes, not 80?

Edit: Sorry, I see what's going on now - you've skipped some COCO classes. Ignore
