### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'layer'

### ISSUE THREAD

**Issue by junyongyou** [xuannianz/EfficientDet#60]
I installed the packages exactly as indicated in the requirements. Then I tried to train a model using my dataset in CSV format, which I have already used in the keras-retinanet model. Then, I got the follow error when training the model:

> Traceback (most recent call last):
  File "D:/CMR Projects/lice_counting/cmrsoftware/src/efficient_det/train.py", line 360, in <module>
    main()
  File "D:/CMR Projects/lice_counting/cmrsoftware/src/efficient_det/train.py", line 312, in main
    freeze_bn=args['freeze_bn'])
  File "D:\CMR Projects\lice_counting\cmrsoftware\src\efficient_det\model.py", line 224, in efficientdet
    features = backbone_cls(input_tensor=image_input, freeze_bn=freeze_bn)
  File "D:\CMR Projects\lice_counting\cmrsoftware\src\efficient_det\utils\__init__.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "D:\CMR Projects\lice_counting\cmrsoftware\src\efficient_det\efficientnet.py", line 456, in EfficientNetB0
    **kwargs)
  File "D:\CMR Projects\lice_counting\cmrsoftware\src\efficient_det\efficientnet.py", line 394, in EfficientNet
    name='stem_conv')(x)
  File "C:\Users\junyong\AppData\Local\Continuum\anaconda3\envs\steinsvik_env_simple\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 881, in __call__
    inputs, outputs, args, kwargs)
  File "C:\Users\junyong\AppData\Local\Continuum\anaconda3\envs\steinsvik_env_simple\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 2043, in _set_connectivity_metadata_
    input_tensors=inputs, output_tensors=outputs, arguments=arguments)
  File "C:\Users\junyong\AppData\Local\Continuum\anaconda3\envs\steinsvik_env_simple\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 2059, in _add_inbound_node
    input_tensors)
  File "C:\Users\junyong\AppData\Local\Continuum\anaconda3\envs\steinsvik_env_simple\lib\site-packages\tensorflow_core\python\util\nest.py", line 536, in map_structure
    structure[0], [func(*x) for x in entries],
  File "C:\Users\junyong\AppData\Local\Continuum\anaconda3\envs\steinsvik_env_simple\lib\site-packages\tensorflow_core\python\util\nest.py", line 536, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "C:\Users\junyong\AppData\Local\Continuum\anaconda3\envs\steinsvik_env_simple\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 2058, in <lambda>
    inbound_layers = nest.map_structure(lambda t: t._keras_history.layer,
AttributeError: 'tuple' object has no attribute 'layer'

Can anybody help me on this? Thank you very much.

**Comment by junyongyou** [comment]
This is my main(). Do I do something wrong?

`def main(args=None):
    output_folder = r'C:\efficient_net'

    args = {}
    args['annotations_path'] = r'C:\annotation_train.csv'
    args['gpu'] = '0'
    args['classes_path'] = r'C:\mapping.csv'
    args['val_annotations_path'] = r'C:\annotation_test.csv'

    args['snapshot'] = r'C:\fficientnet-b0_weights_tf_dim_ordering_tf_kernels_autoaugment_notop.h5'
    args['snapshots'] = False
    args['snapshot_path'] = os.path.join(output_folder, 'snapshot')
    args['tensorboard_dir'] = os.path.join(output_folder, 'snapshot')

    args['no_snapshots'] = False
    args['no_evaluation'] = False

    args['freeze_backbone'] = False
    args['freeze_bn'] = False
    args['weighted_bifpn'] = True

    args['batch_size'] = 80
    args['phi'] = 0

    args['num_gpus'] = 0
    args['epochs'] = 120
    args['steps'] = 7000

    args['random_transform'] = True
    args['compute_val_loss'] = True

    args['multiprocessing'] = True
    args['workers'] = 1
    args['max_queue_size'] = 10

    # optionally choose specific GPU
    if args['gpu']:
        os.environ['CUDA_VISIBLE_DEVICES'] = args['gpu']

    args['dataset_type'] = 'csv'

    K.set_session(get_session())

    # create the generators
    train_generator, validation_generator = create_generators(args)

    num_classes = train_generator.num_classes()
    model, prediction_model = efficientdet(args['phi'], num_classes=num_classes,
                                           weighted_bifpn=args['weighted_bifpn'],
                                           freeze_bn=args['freeze_bn'])

    # load pretrained weights
    if args['snapshot']:
        print('Loading model, this may take a second...')
        model.load_weights(args['snapshot'], by_name=True)

    # freeze backbone layers
    if args['freeze_backbone']:
        # 227, 329, 329, 374, 464, 566, 656
        for i in range(1, [227, 329, 329, 374, 464, 566, 656][args['phi']]):
            model.layers[i].trainable = False

    # compile model
    model.compile(optimizer=Adam(lr=1e-3), loss={
        'regression': smooth_l1(),
        'classification': focal()
    }, )

    # print(model.summary())

    # create the callbacks
    callbacks = create_callbacks(
        model,
        prediction_model,
        validation_generator,
        args,
    )

    if not args['compute_val_loss']:
        validation_generator = None

    # start training
    return model.fit_generator(
        generator=train_generator,
        steps_per_epoch=args['steps'],
        initial_epoch=0,
        epochs=args['epochs'],
        verbose=1,
        callbacks=callbacks,
        workers=args['workers'],
        use_multiprocessing=args['multiprocessing'],
        max_queue_size=args['max_queue_size'],
        validation_data=validation_generator
    )`

**Comment by gorgeous369** [comment]
@junyongyou Have you solved this problem? I met it too.
