### ISSUE TITLE
python3 inference.py

### ISSUE THREAD

**Issue by sliawatimena** [xuannianz/EfficientDet#74]
I modified inference.py using 
phi=0
model_path = 'checkpoints/2020-02-11/coco_02_1.9017_1.8430.h5'
image_path = '/home/suryadi/d/learn/coco/images/val2017/000000397133.jpg'

```
$ python3 inference.py
Traceback (most recent call last):
  File "inference.py", line 30, in <module>
    prediction_model.load_weights(model_path, by_name=True)
  File "/home/suryadi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 182, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/home/suryadi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1371, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, self.layers)
  File "/home/suryadi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 754, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #338 (named "class_head"), weight <tf.Variable 'pyramid_classification/kernel:0' shape=(3, 3, 64, 180) dtype=float32> has shape (3, 3, 64, 180), but the saved weight has shape (720, 64, 3, 3).

```

How to solve this problem? Thank you very much in advance.

Warmest Regards,
Suryadi

**Comment by xuannianz** [comment]
Hi, the `num_classes`s do not match. You should replace the class name list in `inference.py` with coco class names.
