### ISSUE TITLE
error when using csv data

### ISSUE THREAD

**Issue by amitchavda17** [xuannianz/EfficientDet#77]
Getting this error when using CSV data not using validation set as it is optional
and  annotations are rectangular boxes

> `!python train.py --snapshot imagenet --phi {6} --gpu 0 --random-transform --compute-val-loss --freeze-backbone --batch-size 32 --steps 1000

 

Epoch 1/50
Traceback (most recent call last):
  File "train.py", line 382, in <module>
    main()
  File "train.py", line 376, in main
    max_queue_size=args.max_queue_size,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_generator.py", line 221, in model_iteration
    batch_data = _get_next_batch(generator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_generator.py", line 363, in _get_next_batch
    generator_output = next(generator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/data_utils.py", line 789, in get
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/data_utils.py", line 783, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/data_utils.py", line 571, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/content/EfficientDet/generators/common.py", line 428, in __getitem__
    inputs, targets = self.compute_inputs_targets(group)
  File "/content/EfficientDet/generators/common.py", line 378, in compute_inputs_targets
    annotations_group = self.load_annotations_group(group)
  File "/content/EfficientDet/generators/common.py", line 130, in load_annotations_group
    annotations_group = [self.load_annotations(image_index) for image_index in group]
  File "/content/EfficientDet/generators/common.py", line 130, in <listcomp>
    annotations_group = [self.load_annotations(image_index) for image_index in group]
  File "/content/EfficientDet/generators/csv_.py", line 304, in load_annotations
    [float(annot['x3']), float(annot['y3'])],
KeyError: 'x3'

**Comment by xuannianz** [comment]
Hi @amitchavda17 , it's a bug introduced earlier today, thanks. Kind remind that you should delete the curly brackets after `--phi`.

**Comment by amitchavda17** [comment]
generator error got fixed but now the training cant move ahead of the first epoch
note: not using a validation set as it was optional

`!python train.py --snapshot imagenet --freeze-backbone --phi 0 --gpu 0 --random-transform --weighted-bifpn --batch-size 16 --steps 42 csv annotations.csv classes.csv`

Epoch 1/50
2020-02-21 07:14:26.524485: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 402653184 exceeds 10% of system memory.
2020-02-21 07:14:26.852091: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 402653184 exceeds 10% of system memory.
2020-02-21 07:14:37.435011: I tensorflow/core/profiler/lib/profiler_session.cc:205] Profiler session started.
2020-02-21 07:14:37.436829: E tensorflow/core/platform/default/device_tracer.cc:70] CUDA error: CUDA_ERROR_NO_DEVICE
 1/42 [..............................] - ETA: 16:07 - loss: 4.4728 - regression_loss: 2.6808 - classification_loss: 1.79212020-02-21 07:14:38.895754: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 402653184 exceeds 10% of system memory.
2020-02-21 07:14:39.164856: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 402653184 exceeds 10% of system memory.
 2/42 [>.............................] - ETA: 11:39 - loss: 4.2232 - regression_loss: 2.7472 - classification_loss: 1.47602020-02-21 07:14:50.323270: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 402653184 exceeds 10% of system memory.
41/42 [============================>.] - ETA: 11s - loss: 3.8339 - regression_loss: 2.5518 - classification_loss: 1.2821Traceback (most recent call last):
  File "train.py", line 382, in <module>
    main()
  File "train.py", line 377, in main
    validation_data=validation_generator
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_generator.py", line 332, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/callbacks.py", line 299, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/callbacks.py", line 968, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/callbacks.py", line 987, in _save_model
    filepath = self._get_file_path(epoch, logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/callbacks.py", line 1024, in _get_file_path
    return self.filepath.format(epoch=epoch + 1, **logs)
KeyError: 'val_loss'

**Comment by amitchavda17** [comment]
Created a validation set and made a CSV file for it but still getting some error with it now for anchors

`!python train.py --snapshot imagenet --freeze-backbone --phi 0 --gpu 0 --random-transform --compute-val-loss --weighted-bifpn --batch-size 16 --steps 42 csv annotations.csv classes.csv --val-annotations-path annotations_val.csv`

Epoch 1/50
2020-02-21 08:14:45.094566: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 402653184 exceeds 10% of system memory.
2020-02-21 08:14:45.483064: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 402653184 exceeds 10% of system memory.
2020-02-21 08:14:56.647867: I tensorflow/core/profiler/lib/profiler_session.cc:205] Profiler session started.
2020-02-21 08:14:56.649795: E tensorflow/core/platform/default/device_tracer.cc:70] CUDA error: CUDA_ERROR_NO_DEVICE
 1/42 [..............................] - ETA: 19:04 - loss: 3.8318 - regression_loss: 2.6629 - classification_loss: 1.16892020-02-21 08:14:58.119285: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 402653184 exceeds 10% of system memory.
2020-02-21 08:14:58.471066: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 402653184 exceeds 10% of system memory.
 2/42 [>.............................] - ETA: 13:25 - loss: 3.7955 - regression_loss: 2.5661 - classification_loss: 1.22942020-02-21 08:15:10.416996: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 402653184 exceeds 10% of system memory.
41/42 [============================>.] - ETA: 11s - loss: 3.6724 - regression_loss: 2.5456 - classification_loss: 1.1268Epoch 1/50
Running network: N/A% (0 of 56) |         | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "train.py", line 382, in <module>
    main()
  File "train.py", line 377, in main
    validation_data=validation_generator
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_generator.py", line 332, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/callbacks.py", line 299, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/content/EfficientDet/eval/pascal.py", line 75, in on_epoch_end
    visualize=False
  File "/content/EfficientDet/eval/common.py", line 193, in evaluate
    visualize=visualize)
  File "/content/EfficientDet/eval/common.py", line 90, in _get_detections
    np.expand_dims(anchors, axis=0)])
ValueError: not enough values to unpack (expected 5, got 3)

**Comment by xuannianz** [comment]
@amitchavda17 thanks very much for helping me improve this project and sorry for the inconvenience. I have fixed these two bugs.

**Comment by amitchavda17** [comment]
Hi @xuannianz  I am trying to run inference using phi=3 and just one class 
But not getting results
Erorr:
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
2020-02-29 11:28:41.846822: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-29 11:28:42.922886: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
4.155547380447388
**: cannot connect to X server**
