### ISSUE TITLE
Issue in running inference_quad.py with pretrained model

### ISSUE THREAD

**Issue by rose-jinyang** [xuannianz/EfficientDet#85]
Hello,
Thanks for supporting the quadrangle detection.
But I met an issue in running inference_quad.py with the pretrained model (csv_02_1.6506_2.5878_w.h5) which is provided by you.
That is following:

Traceback (most recent call last):
  File "D:/Works/Jin/Jin-EfficientDet/EfficientDet-master/inference_quad.py", line 60, in <module>
    np.expand_dims(anchors, axis=0)])
  File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1156, in predict_on_batch
    outputs = self.predict_function(inputs)
  File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\python\client\session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [1,150381] vs. [1,200508]
	 [[{{node boxes/mul_1}}]]
	 [[filtered_detections/map/while/Switch_6/_5123]]
  (1) Invalid argument: Incompatible shapes: [1,150381] vs. [1,200508]
	 [[{{node boxes/mul_1}}]]
0 successful operations.
0 derived errors ignored.

This error raises when predict.
Could you help me?
Thank you

**Comment by xuannianz** [comment]
Hi @rose-jinyang ,it is a bug and has been fixed. Thanks.

**Comment by rose-jinyang** [comment]
Thanks for your quick reply.
It works well.
and I have a question more.
Here quadrangle means any shape as well as rotated rectangle ?

**Comment by rose-jinyang** [comment]
Thanks for your quick reply.
