### ISSUE TITLE
Faild in loading a model trained for quadrangle detection

### ISSUE THREAD

**Issue by rose-jinyang** [xuannianz/EfficientDet#86]
Hello
I trained a model for quadrangle detection.
When train the model I used phi=1 in STEP1 command that you provided in ReadMe_quad.
When load the trained model, I met the following issue.
Of course, I used phi=1 in inference_quad.py too.

Traceback (most recent call last):
  File "D:/Works/Jin/Jin-EfficientDet/EfficientDet-master/inference_quad.py", line 43, in <module>
    prediction_model.load_weights(model_path, by_name=True)
  File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 182, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1371, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, self.layers)
  File "C:\Users\admin\Anaconda3\envs\py37_tf1.x\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 754, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #494 (named "box_head"), weight <tf.Variable 'conv2d_3/kernel:0' shape=(3, 3, 88, 108) dtype=float32> has shape (3, 3, 88, 108), but the saved weight has shape (81, 88, 3, 3).

The model trained by me is one for carrot detection rather than text detection.
I think that this is relative to anchor_parameters.
Could you help me?
Thanks

**Comment by xuannianz** [comment]
Hi @rose-jinyang , you may need to modify these lines https://github.com/xuannianz/EfficientDet/blob/c5a0c93acc80a7d7633cde3e9d4e83b023cb2548/inference_quad.py#L23-L25 with `anchor_parameters = AnchorParameters.default` since you are not detecting text.

**Comment by rose-jinyang** [comment]
Okay. It works well.
Thanks for your reply.

**Comment by zouxiaoshi** [comment]
Hi @xuannianz  I met similar problem, and i have changed anchor_parameters to the default parameters, but the problem is still there.


Traceback (most recent call last):
  File "inference_quad.py", line 35, in <module>
    prediction_model.load_weights(model_path, by_name=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 1422, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, self.layers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 820, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #1 (named "stem_conv"), weight <tf.Variable 'stem_conv/kernel:0' shape=(3, 3, 3, 48) dtype=float32> has shape (3, 3, 3, 48), but the saved weight has shape (40, 3, 3, 3).
