### ISSUE TITLE
cannot import name 'Layer'

### ISSUE THREAD

**Issue by wxyhv** [xuannianz/EfficientDet#92]
D:\wxyhv\Anaconda3\envs\tensorflow\python.exe D:/biyecodes/EfficientDet_TensorflowKeras_ByXuannianz/train.py
WARNING:tensorflow:From D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\distributions\distribution.py:265: ReparameterizationType.__init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
WARNING:tensorflow:From D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\distributions\bernoulli.py:169: RegisterKL.__init__ (from tensorflow.python.ops.distributions.kullback_leibler) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Traceback (most recent call last):
  File "D:/biyecodes/EfficientDet_TensorflowKeras_ByXuannianz/train.py", line 21, in <module>
    import tensorflow as tf
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\__init__.py", line 36, in <module>
    from tensorflow._api.v1 import compat
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\_api\v1\compat\__init__.py", line 23, in <module>
    from tensorflow._api.v1.compat import v1
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\_api\v1\compat\v1\__init__.py", line 40, in <module>
    from tensorflow._api.v1.compat.v1 import experimental
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\_api\v1\compat\v1\experimental\__init__.py", line 11, in <module>
    from tensorflow.python.ops.control_flow_v2_toggles import output_all_intermediates
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\control_flow_v2_toggles.py", line 24, in <module>
    from tensorflow.python.ops import control_flow_util_v2
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\control_flow_util_v2.py", line 28, in <module>
    from tensorflow.python.keras.engine import base_layer_utils
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\__init__.py", line 27, in <module>
    from tensorflow.python.keras import applications
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\applications\__init__.py", line 25, in <module>
    from tensorflow.python.keras import engine
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\__init__.py", line 23, in <module>
    from tensorflow.python.keras.engine.base_layer import Layer
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 58, in <module>
    from tensorflow.python.keras.saving.saved_model import save as saved_model
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\saving\__init__.py", line 20, in <module>
    from tensorflow.python.keras.saving.hdf5_format import load_attributes_from_hdf5_group
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 32, in <module>
    from tensorflow.python.keras.utils import conv_utils
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\utils\__init__.py", line 38, in <module>
    from tensorflow.python.keras.utils.multi_gpu_utils import multi_gpu_model
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\utils\multi_gpu_utils.py", line 22, in <module>
    from tensorflow.python.keras.engine.training import Model
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 42, in <module>
    from tensorflow.python.keras import metrics as metrics_module
  File "D:\wxyhv\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 34, in <module>
    from tensorflow.python.keras.engine.base_layer import Layer
ImportError: cannot import name 'Layer'

**Comment by xuannianz** [comment]
Hi @wxyhv ,take a look at `requirements.txt`.Make sure the versions are match with yours,especially tf changes a lot between different versions.
