### ISSUE TITLE
OP_REQUIRES failed at non_max_suppression_op.cu.cc:649 : Internal: Cuda call failed with unknown error

### ISSUE THREAD

**Issue by LehiChiang** [xuannianz/EfficientDet#98]
**Hi,author! 
I have already trained your model on my own dataset as VOC format for 10 epochs. After the 10th epoch, the validation set mAP calculation will start, right?  I have a problem and my code is stuck at this point for almost one hour:**

Running network: N/A% (0 of 56) |                                               | Elapsed Time: 0:00:00 ETA:  --:--:--

**After that, the program threw an unknown error something about cuda or non_max_suppression_op**

``` python
 W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at non_max_suppression_op.cu.cc:649 : Internal: Cuda call failed with unknown error
Traceback (most recent call last):
 File "train.py", line 384, in <module>
    main()
  File "train.py", line 379, in main
    validation_data=validation_generator
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training_generator.py", line 332, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 299, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "F:\yolo\EfficientDet\eval\pascal.py", line 75, in on_epoch_end
    visualize=False
  File "F:\yolo\EfficientDet\eval\common.py", line 193, in evaluate
    visualize=visualize)
  File "F:\yolo\EfficientDet\eval\common.py", line 90, in _get_detections
    np.expand_dims(anchors, axis=0)])
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1156, in predict_on_batch
    outputs = self.predict_function(inputs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Cuda call failed with unknown error
         [[{{node filtered_detections/map/while/non_max_suppression_1/NonMaxSuppressionV3}}]]
         [[filtered_detections/map/while/Switch_4/_2671]]
  (1) Internal: Cuda call failed with unknown error
         [[{{node filtered_detections/map/while/non_max_suppression_1/NonMaxSuppressionV3}}]]
0 successful operations.
0 derived errors ignored.
``` 
**The code didn't throw any error in 1-9 epochs training and validation process, and I don't know why this error come out. Could you please help me with this error?**

**Thanks!**

**Comment by xuannianz** [comment]
Hi @LehiChiang , it should calculate mAP after every epoch. I have never encounter this error, can check the versions of your tf, cuda, cudnn.

**Comment by LehiChiang** [comment]
> Hi @LehiChiang , it should calculate mAP after every epoch. I have never encounter this error, can check the versions of your tf, cuda, cudnn.
> Mine are tf==1.15.2, cuda==10.0, cudnn==7.6.2.

Hi , thanks for your reply! And I'll try later.

**Comment by LehiChiang** [comment]
> Hi @LehiChiang , it should calculate mAP after every epoch. I have never encounter this error, can check the versions of your tf, cuda, cudnn.
> Mine are tf==1.15.2, cuda==10.0, cudnn==7.6.2.

Hi  @xuannianz , thanks for your reply! And I'll try later.
